CoolProp/CoolProp

src/HumidAirProp.cpp

Resolve some issues with HAPropsSI
Closes  #397
Closes  #399
Closes  #400
Closes  #403

Ha props si bugs

---

CMakeLists.txt
Web/coolprop/wrappers/Javascript/index.html

Add missing index.html

---

wrappers/Lua/Makefile

Here I removed the lines that @craigbarnes reported to be unneeded and erroneous.

Lua Wrappers: Removed unneeded lines from Makefile.

---

wrappers/Lua/coolprop.lua
wrappers/Lua/coolprop/capi.c
wrappers/Lua/example.lua

This pull request fixes two functions of the Lua wrapper and makes the interface between Lua and C parts of the Lua wrapper more idiomatic.

Fixes and cleanups for Lua/C interface

---

include/AbstractState.h
include/Ancillaries.h
include/CPmsgpack.h
include/Configuration.h
include/CoolPropFluid.h
include/CoolPropTools.h
include/PolyMath.h
include/Solvers.h
src/Backends/Helmholtz/FlashRoutines.cpp
src/Backends/Helmholtz/FlashRoutines.h
src/Backends/Helmholtz/Fluids/Ancillaries.cpp
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h
src/Backends/Helmholtz/ReducingFunctions.h
src/Backends/Helmholtz/VLERoutines.cpp
src/Backends/Helmholtz/VLERoutines.h
src/Backends/Incompressible/IncompressibleBackend.cpp
src/Backends/Incompressible/IncompressibleFluid.cpp
src/Backends/REFPROP/REFPROPMixtureBackend.h
src/Backends/Tabular/TabularBackends.h
src/CoolPropLib.cpp
src/CoolPropTools.cpp
src/HumidAirProp.cpp
src/PolyMath.cpp
src/Solvers.cpp

Most of these are just cleanups. Still, fixing these and others (105 total) will help in future to easily find new problems, and anyway it improves readability of code

First bunch of Coverity Scan static analysis warning fixes

---

wrappers/Julia/CoolProp.jl

Added the "AbstractState_set_fractions" function in the export list.

AbstractState_set_fractions was not exported

---

Web/coolprop/Tabular.rst
include/CoolPropTools.h
include/PhaseEnvelope.h
src/Backends/Helmholtz/FlashRoutines.cpp
src/Backends/Helmholtz/PhaseEnvelopeRoutines.cpp
src/Backends/Helmholtz/PhaseEnvelopeRoutines.h
src/Backends/REFPROP/REFPROPMixtureBackend.cpp
src/Backends/Tabular/BicubicBackend.cpp
src/Backends/Tabular/TabularBackends.cpp
src/Backends/Tabular/TabularBackends.h
wrappers/Python/CoolProp/AbstractState.pxd
wrappers/Python/CoolProp/AbstractState.pyx
wrappers/Python/CoolProp/cAbstractState.pxd

A bit slower than pures, but still much faster than full

Tabular mixtures work with BICUBIC

---

Web/fluid_properties/HumidAir.rst

There appears to be a missing cell in this table. Added it.

Added missing cell "Input/Output" for enthalpy row.

---

dev/fluids/Novec649.json

Implement Novec649 EOS

---

Web/coolprop/wrappers/Android/index.rst

Now describes manual parameter changes required in CMakeLists.txt, how to change ndk-build options, and how to integrate the generated files into an Android Studio project.

Added details from #820

---

wrappers/Julia/CoolProp.jl

Other update due to `Julia 0.4` changes
+ added `CoolProp` functions

Add high-level functions to Julia wrapper

---

include/AbstractState.h
src/AbstractState.cpp
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h
src/Backends/REFPROP/REFPROPMixtureBackend.cpp
src/Backends/REFPROP/REFPROPMixtureBackend.h

This is a very quick fix for #977 , but it serves my purpose. @ibell , do you see any problems merging this?

Saturation states

---

CMakeLists.txt

Easier to compile CoolProp into other tools

Add target_link_libraries to CMakeLists.txt

---

src/CoolPropLib.cpp
wrappers/Julia/CoolProp.jl

And adapt the julia wrapper so it still works.

Revert part of 763d4ce to solve #1077

---

wrappers/Julia/CoolProp.jl

Adapt Julia Wrapper to #1097 as discussed in #1096
Also enlarge buffer size as discussed in #1093.

Add error handling to some functions, see #1096

---

wrappers/SMath/coolprop_wrapper/Properties/AssemblyInfo.cs.template

SMath wrapper: update AssemblyInfo.cs.template

---

src/CoolPropLib.cpp
wrappers/Julia/CoolProp.jl

Correct AbstractState_set_binary_interaction_double in shared library

---

Web/coolprop/wrappers/SMath/index.rst
dev/buildbot/master/master.cfg
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_HAProps.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_Phase.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_Props.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_Props1.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_get_fluid_param_string.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_get_global_param_string.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_get_param_index.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_get_parameter_information_string.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_saturation_ancillary.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_set_reference_stateD.cs
wrappers/SMath/coolprop_wrapper/Functions/CoolProp_set_reference_stateS.cs
wrappers/SMath/coolprop_wrapper/build_zip.bat.template

I intend to make some steps to allow SMath wrapper to work on mono under Linux, where SMath Desktop Linux works.
Sorry for bad previous attempt - messed up with git.

Prepare to attempt making SMath wrapper work on mono

---

src/Backends/Cubics/CubicBackend.cpp
src/Backends/Cubics/CubicBackend.h

Implement `calc_molar_mass()` for the cubic backend.

Cubic calc_molar_mass, closes #1124

---

include/CoolPropLib.h
src/Backends/Cubics/CubicBackend.cpp
src/Backends/Cubics/CubicBackend.h
src/CoolPropLib.cpp
wrappers/Julia/CoolProp.jl

Add `specify_phase()` to the library
Add `AbstractState_update_and_1_out` to the library
Add the functions in the Julia wrapper
Some enhancement in the Julia wrapper

Export specify_phase() to the library, closes #1133

---

src/Backends/Cubics/VTPRCubic.h

Making use of their feature (aii_term has tau derivative), and only do numeric derivatives for the gE_R term.

Use aii_term and b0_ii from cubic

---

dev/cubics/cubic_fluids_schema.json
src/Backends/Cubics/CubicBackend.cpp
src/Backends/Cubics/CubicBackend.h
src/Backends/Cubics/CubicsLibrary.cpp
src/Backends/Cubics/CubicsLibrary.h
src/Backends/Cubics/GeneralizedCubic.cpp
src/Backends/Cubics/GeneralizedCubic.h
src/Backends/Cubics/UNIFAQLibrary.cpp
src/Backends/Cubics/UNIFAQLibrary.h
src/Backends/Cubics/VTPRBackend.cpp
src/Backends/Cubics/VTPRBackend.h

Set alpha function in JSON

---

src/Backends/Cubics/UNIFAQ.cpp
src/Backends/Cubics/UNIFAQ.h
src/Backends/Cubics/UNIFAQLibrary.cpp
src/Backends/Cubics/VTPRCubic.h

Now `gE_R` has analytical derivatives.
The numerical derivatives are pushed into `ln_gamma_R`

First step toward #1310

---

src/Backends/REFPROP/REFPROPMixtureBackend.cpp
src/Backends/REFPROP/REFPROPMixtureBackend.h
wrappers/Python/CoolProp/AbstractState.pxd
wrappers/Python/CoolProp/AbstractState.pyx
wrappers/Python/CoolProp/cAbstractState.pxd

... to allow for setting departure function

Implement set_binary_interaction_string for REFPROP backend 

---

dev/cubics/cubic_fluids_schema.json
include/Helmholtz.h
src/Backends/Cubics/CubicBackend.cpp
src/Backends/Cubics/CubicBackend.h
src/Backends/Cubics/CubicsLibrary.cpp
src/Backends/Cubics/CubicsLibrary.h
src/Backends/Cubics/GeneralizedCubic.cpp
src/Backends/Cubics/GeneralizedCubic.h
src/Backends/Cubics/VTPRBackend.cpp
src/Backends/Helmholtz/Fluids/FluidLibrary.h
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h
src/Backends/Helmholtz/MixtureParameters.cpp
src/Backends/Helmholtz/VLERoutines.cpp
src/Backends/Helmholtz/VLERoutines.h
src/Helmholtz.cpp

Allow for cubic transformations in HEOS multi-fluid model

---

Web/coolprop/HighLevelAPI.rst
src/Backends/Helmholtz/Fluids/FluidLibrary.cpp
src/Backends/Helmholtz/Fluids/FluidLibrary.h
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp

Add the ability to get the JSON data for a fluid, add docs

Get JSON string for fluid at runtime

---

src/CoolPropLib.cpp

Should correct most of the remaining C4018

Removes some C4018 warnings,  #1413

---

src/Backends/Cubics/UNIFAC.cpp
src/Backends/Cubics/UNIFAC.h

UNIFAC compile errors, closes #1426

---

dev/Tickets/1440.py
wrappers/Python/CoolProp/Plots/Common.py

Fix plotting

---

src/Backends/Cubics/CubicBackend.cpp
src/Backends/Cubics/GeneralizedCubic.h
src/Backends/Cubics/UNIFAC.cpp
src/Backends/Cubics/UNIFAC.h
src/Backends/Cubics/VTPRBackend.cpp
src/Backends/Cubics/VTPRBackend.h
src/Backends/Cubics/VTPRCubic.h

@ibell It compiles under Linux, but I did not checked yet if it works correctly.

Add function to change Q in VTPR

---

.travis.yml
.travis/.travis.fullmatrix.yml
.travis/build_wheels.sh
Web/coolprop/snippets/propssi.cxx
Web/develop/testing.rst
dev/coverity/main.cxx

Use Travis to build and commit a coverity scan. Also includes some of the initial changes from the travis_integration branch.

Coverity scan

---

src/Backends/Cubics/GeneralizedCubic.h
src/Backends/Cubics/UNIFAC.cpp
src/Backends/Cubics/UNIFAC.h
src/Backends/Cubics/UNIFACLibrary.cpp
src/Backends/Cubics/VTPRBackend.cpp
src/Backends/Cubics/VTPRBackend.h
src/Backends/Cubics/VTPRCubic.h

Also set the populated flag (should have been done before)

Add ability to get parameters from the VTPR backend

---

src/Backends/Cubics/CubicBackend.cpp
src/Backends/Cubics/GeneralizedCubic.h
src/Backends/Cubics/UNIFAC.cpp
src/Backends/Cubics/UNIFAC.h
src/Backends/Cubics/VTPRBackend.cpp
src/Backends/Cubics/VTPRBackend.h
src/Backends/Cubics/VTPRCubic.h

@JonWel  Can you please ready this for merging? I need it for fitting.

Vtpr change q

---

CoolPropBibTeXLibrary.bib

the repo is also linked from the paper

conference paper instead of github repo

---

Readme.rst

and explain what to ask where.
please change the text where inccorect or unpolite
The link uses a google shortlink, see statistics by appending a + or .ifno:
https://goo.gl/Pa7FBT
https://goo.gl/Pa7FBT+
https://goo.gl/Pa7FBT.info

link to  google groups in Readme

---

src/Backends/Tabular/TabularBackends.cpp
src/Backends/Tabular/TabularBackends.h

[msgpack] update dependency

---

src/Backends/Helmholtz/Fluids/FluidLibrary.cpp

While indexing was fixed in #1562 for replacing a JSON fluid, it created a slight memory leak (only detected when replacing a fluid several hundred thousand times).  When map[index] is used to replace an existing keyed entry and the second map element is a custom type/object, it must first be erased to properly deallocate the memory before assigning the new map entry at the same keyed index.  This only needs to be done for the ``fluid_map`` and the ``JSONstring_map`` because the map data contains a ``CoolPropFluid`` object and a dynamic ``string`` type, respectively.
Testing shows that after 1 million fluid replacements, the functionality has not changed, the map sizes stay constant, and the memory allocation for the CoolProp module remains rock steady.

Fix slight memory leak when replacing fluid jSON.

---

Web/coolprop/LowLevelAPI.rst

Documentation of Low-Level phase specification added.  Along with PR #1625, this docs update closes #1563.
Reviewers should make sure this captures the "intent" of the ``specify_phase()`` facility, outcomes, and warnings.

Update Low-Level API documentation for imposed phase [skip ci]

---

wrappers/Python/CoolProp/AbstractState.pyx

See https://github.com/CoolProp/CoolProp/issues/1638
Apologies for PR #1639.  Hopefully this one works for you.

fix inconsistent function declarations between AbstractState.pyx and AbstractState.pxd (#1638)

---

src/Backends/Helmholtz/FlashRoutines.cpp
src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
src/Backends/Tabular/TabularBackends.cpp

Closes #1607 with following patches:
These issues in the output below are **_not_** addressed in this PR.
- **TTSE: 1-Phase (imposed or not) fails for SmassT/DmassT input pairs** - Already documented in open issue #1315.  Fails in the **Liquid** and **Supercritical** regions
- **TTSE: 1-Phase (imposed or not) fails for DmassP input pairs in some phase regions** - This is already documented in issue #936.  Fails in the **Gas**, **Supercritical Gas**, and **Supercritical** regions.
Routines were tested in all six phase regions using "R245fa" (output shown here) and "Water" for all input pairs currently accepted by the TTSE Backend.  See Issue #1607 for output before change implementation.
**HEOS Test Results for "R245fa"**
```
CoolProp Version 6.1.1dev
Printing Tables for State Points in: …
```

Fixes Logic Bugs When Imposing Phase on TTSE and HEOS Input Pairs

---

LICENSE

This closes #1685 
Deleted and created via the web interface & template

License issue1685

---

dev/fluids/m-Xylene.json
dev/fluids/n-Butane.json
dev/fluids/n-Decane.json
dev/fluids/n-Dodecane.json
dev/fluids/n-Heptane.json
dev/fluids/n-Hexane.json
dev/fluids/n-Nonane.json
dev/fluids/n-Octane.json
dev/fluids/n-Pentane.json
dev/fluids/n-Propane.json
dev/fluids/n-Undecane.json
dev/fluids/o-Xylene.json
dev/fluids/p-Xylene.json

[ Added aliases for the following fluid species 
m-Xylene.json	
n-Butane.json	
n-Decane.json	
n-Dodecane.json	
n-Heptane.json	
n-Hexane.json	
n-Nonane.json	
n-Octane.json
n-Pentane.json	
n-Propane.json	
n-Undecane.json	
o-Xylene.json	
p-Xylene.json	
]
[ More aliases for access fluid property data ]
[ Fluids with overlapping aliases(no overlaps for the aliases that I added) ]
[ I was hoping that there was a CI tester for PRs. I performed the edits within GitHub.
[ None ]

Fluids alias additions

---

include/AbstractState.h
include/DataStructures.h
src/AbstractState.cpp
src/DataStructures.cpp

I added a shorthand function for the isentropic expansion coefficient. Sorry for the whitespace mess, please visit https://github.com/CoolProp/CoolProp/pull/1791/files?w=1 for a diff without whitespace changes.

Add isentropic expansion coefficient

---

include/AbstractState.h

See https://github.com/CoolProp/CoolProp/issues/1841

fixes in doxygen docu for fundamental derivative

---

wrappers/Python/CoolProp/__init__.py

Fixes issue https://github.com/CoolProp/CoolProp/issues/1876

Update init.py byte string in split for Py3.8

---

Web/index.rst

Adding Tabular online tool, PropieadesDeFluidos
[ *We must be able to understand the design of your change from this description. If we can't get a good idea of what the code will be doing from the description here, the pull request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the wrapper code being implemented, so please walk us through the concepts.* ]
[ *What benefits will be realized by the code change?* ]
[ *What are the possible side-effects or negative impacts of the code …

Update index.rst adding PropiedadesDeFluidos Tool

---

Web/coolprop/wrappers/Csharp/index.rst

Updated info about 3-party wrapper (SharpProp).

Updated info for the C# Wrapper

---

Web/index.rst

Included an example that manages units and other mathematical functions with mathjs
Included a new link for another project from github, this includes a demo that works with units using mathjs thus it can evaluate expressions like: 
* *Density* of **nitrogen** at a *temperature* **25 °C** and a *pressure* **1 atmosphere**: `props('D', 'T', 25 degC, 'P', 1 atm, 'Nitrogen')` shall return `1.1452448929367 kg / m^3`
* *Phase* of **water** at a *pressure* of **1 atmosphere** and **0%** *Quality*: `phase('P',1 atm,'Q',0%,'Water')`shall return `"twophase"`
* *Enthalpy* as a function of …

Included CoolPropJavascriptDemo

---

.github/workflows/BuildSharedLibrary.yml
.github/workflows/coolprop_tests.yml
.github/workflows/documentation.yml
.github/workflows/python_cibuildwheel.yml
.github/workflows/windows_installer.yml
dev/extract_version.py

Configure upload to pypi/testpypi
Figure out the next available version to avoid override (especially for testpypi, shouldn't happen for pypi as we should bump in CMakeLists)

Configure upload to pypi/testpypi

---

.github/workflows/python_cibuildwheel.yml
dev/extract_version.py

@ibell mac has a weird sed version, it doesn't behave like the one I have on Ubuntu and git bash... I found the syntax to make it work, but I chose to do the replacement from python instead of using sed to avoid having obscure issues.

Fix mac sed

---

.github/workflows/python_cibuildwheel.yml

Trying to get the upload to work. The current one is having problems in the upload step: https://github.com/CoolProp/CoolProp/runs/5977281354?check_suite_focus=true#step:6:8

Python bindings upload to (test)pypi fixes

---

Web/coolprop/wrappers/Python/index.rst

[Added info about PyFluids (3-party wrapper)](https://github.com/CoolProp/CoolProp/commit/83ecd48ec2ea1a63bc6fc12b1ab014b4f8338580).

Added info about PyFluids (3-party wrapper for Python)

---

Web/coolprop/wrappers/Csharp/index.rst

[Updated info about SharpProp (3-party wrapper)](https://github.com/CoolProp/CoolProp/commit/17b2292eb2c6b0b66ae48f1eae785e7560c1a663).

Updated info about SharpProp (3-party wrapper for C#)

---

.github/workflows/python_cibuildwheel.yml

Reverts CoolProp/CoolProp#2270
and update Cython version to be strictly less than 3.0

Revert "Fix failing python_cibuildwheel workflows" and update

---

.github/workflows/javascript_builder.yml
.github/workflows/release_all_files.yml
.github/workflows/windows_installer.yml
Web/coolprop/wrappers/Javascript/index.rst

I have updated the Javascript docs and added the emscripten build to the GitHub actions.

Add javascript to the release script

---

Web/index.rst

We have changed the name of the app
CuadernoDeProblemas -> pSolver.
pSolver can be used on English and Spanish

App name change: CuadernoDeProblemas -> pSolver, Update index.rst

---

Web/coolprop/wrappers/Excel/index.rst

* Updated the Mac docs for enabling the Excel wrapper
* Using `DYLD_LIBRARY_PATH` has not worked for MacOS (OSX) since about 2015, and so that section has been removed. Trying to debug this stuff was a red herring for me when things don't work at first.
* Users with M1/M2 Macs are instructed to compile their own CoolProp library. (Alternatively, the x86_64 library may be used via Rosetta -- see #2139. It might be worth bringing some of those instructions to this PR. I can do so if requested.)
Clearer instructions for Mac users.
None.
N/A
Closes #1430. Closes #2040. Closes #2224. Closes #1575.

update Excel-wrapper for Mac docs

---

src/Backends/IF97/IF97Backend.h

IF97 calls with PH or PS inputs (_reverse functions of (P, H) and (P, S)_) were failing to return temperatures (and then other property values) in the correct phase due to (published) uncertainties of ±25 mK in the IF97 reverse temperature equations.  For state points very close to the saturation curve, this would periodically result in temperatures in the opposite phase, on the other side of the saturation curve, resulting in other properties being returned from the wrong phase.  This condition has been fixed in the external IF97 module and tested extensively there outside of CoolProp (see CoolProp/IF97#49).
This change:
1. Bumps the IF97 version in CoolProp to include the patches to IF97.
2. Makes phase determination based on the input PH and PS values rather than the resulting PT at …

Improve Robustness of IF97 Reverse (P,H) and (P,S) Evaluations Along Saturation Curve

---

.github/workflows/python_buildwheels.yml

Hopefully the new arm64 image on actions will work, and yield reasonable build times

Enable for windows, no cross for linux

---

dev/generate_headers.py

Based file modification times. The hash-based method is good, but quite slow as files get larger

Add rudimentary dependency management on header generation

---

Web/coolprop/wrappers/MathCAD/MathcadPrime.rst
wrappers/MathCAD/Prime/README.md
wrappers/MathCAD/README.md

Update Web page and README docs to include:
- Instructions for compiling with newer versions of Visual Studio (CMake flag change for bitness)
- Update Mathcad Prime version numbers
- Fix some previous .rst and .md formatting issues 
Help users compile with current set of tools.
None.
N/A - No code changes, skipping CI steps.  Will review Web changes once posted and rendered.
none.

Update Mathcad wrapper docs [skip-ci]

---

include/AbstractState.h
include/CachedElement.h
src/AbstractState.cpp

Not clear much more optimization is possible
Closes #2543

Implement the array-based caching in AbstractState. 

---

src/emscripten_interface.cxx

Export additional API functions to the [JavaScript wrapper](https://coolprop.org/coolprop/wrappers/Javascript/index.html#javascript).
More complete and consistent API surface
Slightly larger API surface
We've been running this in an internal fork of CoolProp for a couple of years with no issues.
N/A

Export additional JavaScript functions

---

src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
src/Tests/CoolProp-Tests.cpp

See #2622  for problem investigation
Closes #2622

Add fallback method for density solver for bad EOS
