CoolProp/CoolProp

src/Backends/Helmholtz/FlashRoutines.cpp, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, src/Backends/Helmholtz/PhaseEnvelopeRoutines.cpp, src/Backends/Helmholtz/VLERoutines.cpp, src/CoolProp.cpp, src/CoolPropLib.cpp, src/Helmholtz.cpp
Here are some fixes:
1. restructuring the fix in CoolProp.cpp for #483;
2. return result of redirect_stdout DLL function (allowing for error handling);
3. fixes for "Local declaration hides local" warnings - there seem to be a number of unnecessary variables, and even one variable declaration that masks return value (iclosest in PhaseEnvelopeRoutines::is_inside())
4. restructuring get_fluid_param_string() exception handling to simplify and unify it; removes two identical code runs.
=> Some more static analyser warning fixes

include/CoolPropTools.h, include/DataStructures.h, src/Backends/Helmholtz/Fluids/FluidLibrary.h, src/Backends/Helmholtz/HelmholtzEOSBackend.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h, src/Backends/Helmholtz/MixtureParameters.cpp, src/Backends/Helmholtz/MixtureParameters.h, src/CoolPropTools.cpp, src/HumidAirProp.cpp
1. Started to optimize function arguments to use refs (more to come)
2. Fixed some things in _HAPropsSI_inputs
=> Avoid copying of parameters; some fixes for _HAPropsSI_inputs

CMakeLists.txt, include/CoolPropTools.h, src/CoolPropTools.cpp, wrappers/Python/setup.py
In the end it wasn't much code...
=> Implement checking of directory size

include/Exceptions.h
1. add integer codes to exceptions (to address #381 No1);
2. restructure derived exceptions to be specializations of templated
classes to make their definitions more compact, and remove code
duplication.
=> Exceptions restructured

src/CoolPropTools.cpp, src/DataStructures.cpp
This time I tested everything under Ubuntu.
-> I reworked primitive structures simplification. This time I don't use c++11 syntax
```c++
var = struct{init_list}
```
Instead, good old structure initializer
```c++
var = {init_list}
```
is used. I'm doing this to allow compiler to compile these primitive structures into library as blobs, ready to use without initialization. They are anyway only needed to initialize smart classes. Now it looks like this:
- strings and numbers are stored in the library binary (data section) and loaded into the memory on library load
- this data is used to initialize array of structs (using a number of calls to struct contructor, and to std::string constructors inside)
- this array is used to initialize static info class object (through its constructor).
I hope …
=> Primitive structures simplification attempt 2

src/Backends/Tabular/TabularBackends.h
Seems to be missing in the list.
=> Add `calc_rhomolar_critical` closes #748

src/Backends/Tabular/TabularBackends.cpp
Outputs are now only generated thanks to debug_level.
=> Supress the outputs when genrating tables, close #865

include/CoolPropTools.h, src/Backends/Helmholtz/TransportRoutines.cpp, src/Helmholtz.cpp, wrappers/Python/CoolProp/AbstractState.pxd, wrappers/Python/CoolProp/AbstractState.pyx, wrappers/Python/CoolProp/CoolProp.pxd, wrappers/Python/CoolProp/CoolProp.pyx, wrappers/Python/CoolProp/cAbstractState.pxd, wrappers/Python/CoolProp/typedefs.pxd
Remap CoolPropDbl to actually be a double, not a long double, in preparation for removal of CoolPropDbl entirely.
closes #931
=> Remap CoolPropDbl to double

wrappers/Julia/CoolProp.jl
Some change in Julia 0.4 have occurred since the last update of this wrapper.
This update should now ensure better behaviour with Julia 0.4 which is now in release state.
https://raw.githubusercontent.com/JuliaLang/julia/0ff703b40afddf9b705bd6a06d3a59cb4c089ea5/NEWS.md
=> Remove warnings when using Julia 0.4 realease

src/CoolPropLib.cpp
Put the catch in a more useful way and solves the call to CoolProp::get_parameter_information:
The `int key = CoolProp::get_parameter_index(param);` will trigger the catch if the `param` is not valid (as no `int` is furnished in that case), which will give the correct output message now.
When `param` is valid, this will run the corrected `CoolProp::get_parameter_information(key, "long")`.
=> Correct get_parameter_information_string, fixes #974

wrappers/MathCAD/CoolPropMathcad.cpp
The Mathcad library header, mcadincl.h, defines a STRING constant.  This
should be MC_STRING, as STRING is too dangerous and conflicts with
STRING enumeration value in format.h from external/cppformat.
=> Fixes STRING conflict between Mathcad library and cppformat

src/Backends/Helmholtz/PhaseEnvelopeRoutines.cpp, src/Backends/Helmholtz/VLERoutines.h, src/Backends/REFPROP/REFPROPMixtureBackend.cpp
int vs unsigned in several comparisons and one initialization.  Wrapped the unsigned values with int().
=> Fixed Minor MSVC Compiler Warnings

wrappers/SMath/coolprop_wrapper/coolpropPlugin.cs
Looking around I think this change should be related to the issue #985
Since double.NegativeInfinity and double.PositiveInfinity are valid results from the solvers and SMath.Math.Numeric.TDouble(result) can't handle these values directly, this patch allows the users to see  ∞ / -∞ as results on the canvas
=> Enable infinity in MakeDoubleResult

.gitignore, src/CoolPropLib.cpp
Do not try to call possibly throwing get_parameter_index if Props1SI
already returned an error
Also, add include/cubic_fluids_schema_JSON.h to gitignore
=> One small tweak to Props1

.gitignore, include/CoolPropLib.h, src/CoolPropLib.cpp, src/CoolPropLib.def, wrappers/Julia/CoolProp.jl
Shared library:
- Export set_binary_interaction_double
Julia wrapper:
- Precompile at first load for Julia 0.4
- Add functions: 
- set_binary_interaction_double
- AbstractState_update_and_common_out
- AbstractState_update_and_5_out
=> Export set_binary_interaction_double + Julia wrapper improvement

src/CoolPropLib.cpp
There are also some exceptions that do not use this new `HandleException` function yet as they don't use the errcode and message buffer (they just set the error string):
```C++
catch (std::exception &e){ CoolProp::set_error_string(e.what()); }
catch (...){ CoolProp::set_error_string("Undefined error"); }
```
Should we do a second function to handle that case?
Some functions like `AbstractState_update_and_common_out` do not have the `CoolPropBaseError` in the previous code. This will be also tested now, but should not be a problem (the `HandleError` is triggered first).
=> Refactor exceptions in CoolPropLib.cpp close #1200

src/Backends/Cubics/CubicBackend.cpp
The transient_pure_state has no mole fractions when created, this was triggering a CoolProp: `Mole fractions must be set` error.
I guess it's because that transient state is supposed to be pure, but this fix allows to get the answer.
Is there something more elegant to do?
=> Solves a bug with cubic and mixtures

src/Backends/Cubics/VTPRBackend.h
The copy was previously creating PengRobinson instances for SatV and SatL, thus, for mixtures, calls like "QT_INPUTS" where giving identical results as PR.
=> SatL and SatV of type VTPR too

src/Backends/Cubics/UNIFAQ.cpp
The value of lnGammag was not cleared, this was creating a sort of caching issue.
(@ibell this solves the issue I was had in Paper1, I finally got it)
=> Solves a bug in VTPR

src/Backends/Helmholtz/VLERoutines.cpp
Also lower a bit the threshold for `df` and add some comments.
=> Correct typo, see #1270

src/Backends/Cubics/VTPRBackend.cpp
Allows for instance to retrieve the critical values used for the pure components in VTPR.
Was always false before.
=> Add pure fluid check to VTPR

include/AbstractState.h, include/CoolPropLib.h, src/Backends/Cubics/CubicBackend.cpp, src/Backends/Cubics/CubicBackend.h, src/Backends/Cubics/GeneralizedCubic.cpp, src/Backends/Cubics/GeneralizedCubic.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h, src/CoolPropLib.cpp, wrappers/Julia/CoolProp.jl
Allows to set coefficients for Mathias-Copemann and TWU from the shared library.
Functionality also added to the Julia Wrapper
=> Export cubic's alpha functions

.gitignore, include/AbstractState.h, src/Backends/IF97/IF97Backend.h
Only implemented the trivial parameters that are defined in IAPWS Guides or the IAPWS-IF97 release.  The only exception is the acentric factor which is calculated from P @ Tr=0.7 and Pcrit.  Had to add an extra virtual function to AbstractState.h (calc_rhomass_critical) to allow for mass based IF97 calculations.  This function will be ignored by the other backends.
Function verification (through Mathcad) is shown in attached.
Slight adjustment to .ignore also to allow for other build directories starting with "build".
=> Add Trivial Parameter calls to IF97 Backend

wrappers/Julia/CoolProp.jl
As discussed in #1293 , we need something at least of size 14 301, so 20 000 should do the trick for now.
=> Bigger buffer size for Julia wrapper

src/Backends/IF97/IF97Backend.h, wrappers/MathCAD/CoolPropMathcad.cpp
Partial verification (through Mathcad wrapper) shown below.  You may want to verify that Cpmass, Cvmass, and speed of sound are properly throwing the exception messages (e.g. in Python) as I can't see them in Mathcad yet.
=> Added PQ and QT Input Pairs to provide Saturation Values to IF97 Backend

src/Backends/REFPROP/REFPROPMixtureBackend.cpp
Create a pull request to solve issue #1368. When the `REFPROPMixtureBackend::version()` is called, the method will return `n\a` when `REFPROPMixtureBackend::REFPROP_supported()` returns `false`. This should prevent the segmentation fault when getting the REFPROP version if REFPROP is not installed. What do you think? Is returning 'n/a' a good solution or do you prefer to raise a ValueError when `SETUPdll == NULL`? My reasoning behind this implementation is that a complete check if REFPROP is supported and safe to load was already implemented in `REFPROP_supported()`, so it would make sense to just trust the value it returns.
P.S. I noticed that my editor removed some trailing white spaces I hope this is not a problem?
=> Return 'n/a'  REFPROP version when not loaded or supported.

src/Backends/REFPROP/REFPROPMixtureBackend.cpp, src/Backends/REFPROP/REFPROPMixtureBackend.h
Not the length of components
Also fix melting line function in REFPROP wrapper
=> In REFPROP wrapper, always pass around vectors of length 20

include/AbstractState.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h
this allows for setting reference state without changing the state of
the JSONLibrary (now without C++11)
=> set_reference_state for AbstractSate

src/Backends/Cubics/GeneralizedCubic.h, src/Backends/Cubics/UNIFAQ.cpp, src/Backends/Cubics/UNIFAQ.h, src/Backends/Cubics/VTPRBackend.cpp, src/Backends/Cubics/VTPRBackend.h, src/Backends/Cubics/VTPRCubic.h
For instance, for a mixture with Ethane and Acetone:
```Julia
AbstractState_set_binary_interaction_double(AS,1, 9, "aij", 433.6)
AbstractState_set_binary_interaction_double(AS,9, 1, "aij", 199)
AbstractState_set_binary_interaction_double(AS,1, 9, "bij", 0.1473)
AbstractState_set_binary_interaction_double(AS,9, 1, "bij", -0.8709)
AbstractState_set_binary_interaction_double(AS,1, 9, "cij", 0)
AbstractState_set_binary_interaction_double(AS,9, 1, "cij", 0)
```
Allows to use Dortmund's parameters instead of Poling's.
Also reduces execution time of VTPR (cut by ~39% in my QT_INPUTS test case) by moving a part of pure fluid code that do not need to be executed more than once and by saving the values of Psi instead of calling it a lot of time.
It still much heavier than PR (around 10 times in my …
=> Set VTPR constants through the set_binary_interaction_parameter function, closes #1311

include/CoolPropLib.h
Non-closed quote block comments out function
=> Fix typo in CoolPropLib.h

wrappers/MathCAD/CoolPropMathcad.cpp
Closes #1462 .  Tracked to legacy code in Mathcad wrapper that used standard memory allocation methods for strings (`new`) instead of using the provided `MathcadAllocate()` function, which allows Mathcad 15 and Prime to track and release memory allocations when they are no longer needed and provides consistent memory allocation across DLL boundaries.  This didn't cause a crash in either Mathcad version when compiled with VS2010, but does with VS2015 and may have been causing an undetected memory leak.  No sign of a memory leak now.  Two functions were affected, `get_global_param_string()` and `get_fluid_param_string()`.
Interestingly, I found S. Polak's inquiry about this very issue on the [Mathcad support forum](https://www.ptcusercommunity.com/thread/51416) in 2012.  It was answered …
=> Update Mathcad wrapper to use MathcadAllocate() for returned strings.

wrappers/MathCAD/CoolPropMathcad.cpp, wrappers/MathCAD/CoolProp_EN.xml
Low level mixture parameter functions added:
Mathcad function documentation was also updated for these three functions.
Should be used with caution in Mathcad, but can successfully be used to add binary pairs to the rule set and adjust mixing parameter values.  Example from the web documentation shown here in Mathcad for verification:
=> Added low-level binary parameter functions to Mathcad wrapper

wrappers/Python/setup.py
I was trying to work on another feature but needed to fix this first before moving forward. Please check if it can be merged. Thanks.
To solve the *ValueError* encountered during the compilation of Python wrappers using Cython 0.26:
```
Traceback (most recent call last):
File "setup.py", line 305, in <module>
ext_modules = cythonize(ext_modules, compiler_directives = cython_directives)
File "C:\Users\User\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 886, in cythonize
c_options = CompilationOptions(**options)
File "C:\Users\User\Anaconda3\lib\site-packages\Cython\Compiler\Main.py", line 568, in __init__
raise ValueError(message)
ValueError: got unknown compiler directive: embed_signature
```
Cython 0.26 changes its compiler directive name from *embed_signature* to …
=> Change for compiler directive name in Cython 0.26

src/AbstractState.cpp
I would like to use CoolProp to calculate the first-order derivative of isochoric specific heat, isobaric specific heat and speed of sound, and I am writing the corresponding code in AbstractState.cpp using the formulas as described below:
Cv: second-order derivative of specific internal energy
Cp: first-order derivative equations following Thorade and Saadt (2013) like all the other derivatives in CoolProp
Speed of sound: with the formula in the following pdf and LaTeX file
[first_derivative_speed_of_sound.pdf](https://github.com/CoolProp/CoolProp/files/1184575/first_derivative_speed_of_sound.pdf)
[first_derivative_speed_of_sound .txt](https://github.com/CoolProp/CoolProp/files/1184576/first_derivative_speed_of_sound.txt)
Unfortunately, I am unable to build the Catch testrunners and …
=> Calculation of first-order derivatives of isochoric specific heat, isobaric specific heat and speed of sound

Web/coolprop/wrappers/Octave/index.rst
As -std=gnu++11 option is required but disabled by default.
=> Add CXX11 flag for octave build

src/Backends/Helmholtz/Fluids/FluidLibrary.cpp, src/Backends/Helmholtz/Fluids/FluidLibrary.h
As discussed in issue #1548, when a JSON fluid is added to the FluidLibrary, replacing a fluid that already exists, as in the example in the High-Level Interface docs, the fluid_map gets corrupted.  The fluid to be replaced is being erased from the fluid_map, and then added back in at the max index + 1.  Unfortunately, the fluids with higher indices are not re-indexed, and so the last fluid in the list (Xenon in this case) gets overwritten.  Future references to Xenon then pull all fluid info and properties for the fluid that was re-inserted; the Xenon data is lost.  Logic is not flawed when new fluids are added, as they are when the initial JSON library is loaded.
The fix proposed here to the `JSONFluidLibrary:add_one` routine does not erase the fluid to be replaced, but sets the …
=> Fixes out-of-sync fluids map when replacing a JSON fluid.

.gitignore, wrappers/Python/setup.py
With release of Visual Studio 2017 and 2018, VS2015 (vc14) may not be the highest default on the machine.  Python wrapper setup.py needed a cmake-compiler option for vc14 to force use of VS2015 (required for Python 3.5 & 3.6) for the build when higher compiler versions exist on the machine.
Also added some ignores for Python wrapper build files left behind when building right in the local git repo.
=> Added Python wrapper CMake generator for vc14 for when default is higher

Web/Makefile, Web/_static/.gitignore, Web/coolprop/.gitignore, Web/coolprop/HighLevelAPI.rst, Web/coolprop/LowLevelAPI.rst, Web/coolprop/wrappers/Python/.gitignore, Web/coolprop/wrappers/Python/index.rst, Web/coolprop/wrappers/index.rst, Web/develop/documentation.rst, Web/fluid_properties/.gitignore, Web/fluid_properties/IF97.rst, Web/fluid_properties/Mixtures.rst, Web/fluid_properties/index.rst, Web/fluid_properties/methane-ethane.py, Web/scripts/.gitignore
This is strictly a Documentation update (closes #1501 ). Changes include:
This is a clean PR that replaces #1547 that got too far out of date.  @ibell & @jowr there are only minor changes from what you looked at before.  Because of the various areas affected, not sure if you want this to be "squashed" or maintain the separate commits as a documentation trail.
=> Documentation Update

include/CoolProp.h, src/Backends/Helmholtz/FlashRoutines.cpp
Fixes #1602 (see that issue for behavior).  Low-level calls to update on saturation line reset internal variable ``_phase`` to ``iphase_twophase``.  Subsequent single phase calculation using PT_flash did not check to see if ``_phase`` had gotten out of sync with ``imposed_phase_index``.
Tested with Python script:
```python
import CoolProp
p_Pa = 15E5
T_K = 400
HEOS = CoolProp.AbstractState('HEOS','D2O')
print("PT Update with no phase set:")
HEOS.update(CoolProp.PT_INPUTS, p_Pa, T_K)
print("hmass = {:.2f} kJ/kg".format(HEOS.hmass()/1000.0))
print(" ")
print("PT Update with iphase_liquid imposed")
HEOS.specify_phase(CoolProp.iphase_liquid)
HEOS.update(CoolProp.PT_INPUTS, p_Pa, T_K)
print("hmass = {:.2f} kJ/kg".format(HEOS.hmass()/1000.0))
print(" ")
print("PQ Update on saturation curve") …
```
=> Patch PT_flash() to update _phase with imposed phase, in case it changed

src/CoolProp.cpp
This PR closes #1603 and also closes #969 .
In High-Level interface only, when parsing the mixture string, do not add mixture components that have a mole fraction of 0 (or negative, which is nonsensical).  Unfortunately, cannot be applied to the low-level interface.
Tested in Mathcad wrapper (curiously, error could not be reproduced in Python wrapper, at least for this example).
=> Parse out zero mole fraction components in PropsSI()

src/CoolProp.cpp
Closes #1631 
If phase can't be determined, because of an error in PropsSI() or the state point location, PhaseSI() returned a blank string:
```python
In: PhaseSI("T",270.3895839,"P",264626.0542,"R134a")
Out: ''
```
Modified PhaseSI() to instead return "unknown", appended with any error messages from the call to PropsSI():
```python
In: PhaseSI("T",270.3895839,"P",264626.0542,"R134a")
Out: 'unknown: Saturation pressure [264626 Pa] corresponding to T [270.39 K] is within 1e-4 % of given p [264626 Pa] : PropsSI("Phase","T",270.3895839,"P",264626.0542,"R134a")'
```
=> Provide return string from PhaseSI() if phase can't be determined.

wrappers/Python/CoolProp/Plots/Common.py
Hi,
This pull request corrects a little mistake in function "inline_label" in CoolProp/Plots/Common.py in the python wrapper
=> Mistake in function 'inline_label' in CoolProp/Plots/Common.py

Web/coolprop/HighLevelAPI.rst, include/DataStructures.h, src/CoolProp.cpp, wrappers/MathCAD/CoolPropMathcad.cpp
**_PropsSI()_** is updated to allow the phase to be imposed by tagging one of the input key strings with the pipe symbol, **"|"** followed by a phase string (e.g. "**T|liquid**" or "**P|supercritical_gas**").  If a valid phase string is found, **_State_**->**_specify_phase()_** is called with the corresponding phase index before the call to **_update()_**.  Only one Input key string can be tagged with a phase string and error checking makes sure that:
- Imposed phase is a valid phase string
- Only one Input key is tagged with a phase
- Phase strings prefixed with "phase_" or "iphase_" are acceptable
High-Level Interface documentation is also updated to explain how to use this feature.  It has been successfully tested in both Python and Mathcad wrappers (updated to catch phase syntax …
=> Update PropsSI() to Parse Imposed Phase Strings on Input Keys

src/CoolProp.cpp
Patches #1660.  Mods to ``StripPhase()`` in CoolProp.cpp to handle (or reject) backends that don't have phase functions like calc_phase() and specify_phase().  Specifically REFPROP and INCOMP and IF97 backends were affected.  Tests should all pass now.
Error message was something like:
```python
In [1]: PropsSI('C','T',500,'P',101325,'INCOMP::DowQ')
ValueError: This backend does not implement calc_phase function : PropsSI("C","T",500,"P",101325,"INCOMP::DowQ")
```
With the patch, these backends are all passing tests:
```python
In [4]: PropsSI('C','T',500,'P',101325,'INCOMP::DowQ')
Out[4]: 2288.1643758645673
In [7]: PropsSI("D","P",101325,"T",375,"REFPROP::Water")
Out[7]: 0.5944246707421037
In [8]: PropsSI("D","P",101325,"T|gas",375,"REFPROP::Water")
Out[8]: 0.5944246707421037
In [9]: …
```
=> Patches PropsSI imposed phase for backends other than HEOS

include/Configuration.h, src/CoolProp.cpp
Locale is specified by configuration variable FLOAT_LOCALE_NAME
Cannot use the system-default locale because some things (e.g., naughty matplotlib) change the system locale and it cannot be relied upon to be stable.
Closes #1551 
Closes #1662 
Closes #1647
=> Make string->float conversion aware of the locale

CMakeLists.txt
Added DARWIN_USE_LIBCPP cmake flag to allow for OSX builds to use the libc++ library.
This was needed by me since another project was built with libc++ and it caused issues trying to call CoolProp from it, adding cxx make flags did not work since libstdc++ was hard coded in the CMakeLists. Allows for and closes #1671
=> Let DARWIN build with libc++

CODE_OF_CONDUCT.md, CONTRIBUTING.md, FAQ.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, Readme.rst
Adding QA docs to get us up to Github recommended standards per discussion with @ibell.  These QA Docs are intended to:
- encourage contributions to the CoolProp project through README update and CONTRIBUTING guidelines
- encourage "better" Issues and Pull Requests with needed information through Issue and Pull Request templates
- encourage a positive community environment
Core developers and contributors alike are encouraged to review these and submit any "tweaks" that are deemed necessary.  Also polished up formatting of FAQs and added a couple of new items that come up with some frequency.
=> Adding Github QA docs for contributing

.gitmodules, .travis.yml
This is a follow-up for #1610 
Turns out it does not save a significant amount of time.
One could also remove the submodule_depth again, and only keep the other changes:
sorted the submodules alphabetically, specified to use master branch, and pulled the latest master
=> Submodules track master branch

Web/coolprop/wrappers/Excel/index.rst
If the Excel add-in file "CoolProp.xlam" is manually installed, the full path to the xlam file appears in the cells with CoolProp functions after restarting Excel. And the function evaluations of the cells always fail. This problem seems to be due to the Windows security feature which automatically blocks the files downloaded from the internet. This problem is avoided by unblocking the xlam file in the properties window of the file.
I verified the workaround on my Window 10 PC in Japan as a following figure:
This solved the problem perfectly.
``#1180``: already closed, but this is a new workaround.
=> Add a short note to the documentation of Excel wrapper

Web/coolprop/wrappers/StaticLibrary/index.rst
This change is the result from the user group ?: https://groups.google.com/forum/#!topic/coolprop-users/bI01hf8sQnY
Update an index.rst with a note on how to compile coolprops in debug with gcc.
Makes it easier for users to figure out why their debug build is missing symbols with gcc.
None.
Linked a debug library with the build cool props debug, and it worked as expected.
*Describe the actions you performed (e.g. text you typed, commands you ran, etc.), and describe the results you observed.*  
*Please attach here any python test sessions or image captures of testing in other …
=> Add a compile note for gcc debug build

src/Backends/REFPROP/REFPROPMixtureBackend.cpp, src/Backends/REFPROP/REFPROPMixtureBackend.h, src/Configuration.cpp
Added functions to force the loading and unloading of the REFPROP library. This allows you to change the REFPROP version at runtime and not only at times when not REFPROPMixtureBackend instance is alive. 
This is not thread-safe, but I guess all of the REFPROP-related is like this.
=> Force unloading of REFPROP upon path change

include/Ancillaries.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, wrappers/MathCAD/CoolPropMathcad.cpp
Modify ``get_surface_tension()`` in the ``HelmholtzEOSMixtureBackend`` to check the ``_phase`` variable and throw a meaningful error unless ``_phase == iphase_twophase``. 
Alerts user that the input pair results in a state that is not in the two phase region when Surface Tension is requested.  
PT Input pairs on the saturation curve should probably allow surface tension to be returned.  However, ``PropsSI()`` calculates the state point first and then returns the requested output parameters; causing a different error message to be thrown deeper in the solver that the inputs are too close to the saturation curve (and the desired two phase region).  This isn't easy to intercept and bypass cleanly.  Surface Tension should usually be requested with PQ or QT input pairs anyway.
- *How did you …
=> Throw sensible error message if single-phase surface tension requested

wrappers/Mathematica/CoolPropMathematica.cpp
- Fix memory leak, see https://github.com/CoolProp/CoolProp/issues/1759
- Remove irrelevant code which appeared to be a test function.
- Change `mreal` to `double` and remove casts. Recent versions of Mathematica use `double` instead of `mreal`. In older versions, `mreal` is a typedef for `double`.
Compiled the library and checked the example notebook
Closes #1759
=> Free input strings in Mathematica interface

src/CoolProp.cpp
Prior to 6.2.0, an error sometimes occurred if a user defined mixture with many components contained a component with a zero (0) mass fraction. PR #1628 modified PropsSI() to parse out any zero mass fraction components from the mixture fluid string and calculate the mixture based on the remaining components.  This had an adverse effect on incompressible fluids which can used the same [] syntax to specify the solute mass/volume fraction in water, which is allowed to be zero.  The change in PR#1628 would then strip out the incompressible fluid leaving an empty and invalid fluid string as reported in Issue #1756.
Change was to prevent a zero mass fraction component from being stripped if there is only one component in the fluid list (as is the case for incompressible fluids).  The …
=> Patch PropsSI for INCOMP fluid with zero mass fraction

Web/develop/backends.rst, Web/index.rst
Add IF97 page link to CoolProp homepage and develop/backends page.
Advertises IF97 capability on CoolProp homepage and provides link to the doxygen IF97Backend Class Reference for easier lookup.
Simple link additions.  Will verify once the dev/docs are built.
Per @ibell request in #1762.
=> Add IF97 links to CoolProp homepage and backends page

src/AbstractState.cpp, wrappers/MathCAD/CoolPropMathcad.cpp
Modified the IF97 Abstract State Generator to throw an error if the fluid name is anything other than "Water" or "H2O".
The IF97 backend would allow fluid strings like:
- "IF97::Water" (_OK_)
- "IF97::H2O" (_OK_)
- "IF97::Propane" (_not OK_)
- "IF97::Water[0.5]&Ethanol[0.5]" (_not OK_)
While it should be obvious that IF97 only returns Water properties, this call (which does not throw an error or warning) could be confusing or mis-leading:
```
In [5]: CP.PropsSI("D","T",295,"P",101325,"IF97::Propane")
Out[5]: 997.806810732084
In [6]: CP.PropsSI("D","T",295,"P",101325,"IF97::Water[0.5]&Ethanol[0.5]")
Out[6]: 997.806810732084
```
Throwing an error if attempting to initialize the IF97 backend with anything other than Water removes any ambiguity.
- Does not check for any other potential …
=> Disambiguate IF97 Fluid Names - Water only

Web/coolprop/wrappers/Python/index.rst
As discussed in #1777, this PR introduces instructions to install the Conda package from the conda-forge channel.
This installation method supports those users with Conda distributions of Python.
Conda-forge may decide to stop maintaining the package, resulting in these instructions becoming out of date.
I did not do any verification of this change.
=> Add conda install instructions from conda-forge

src/Backends/REFPROP/REFPROPMixtureBackend.cpp, src/Backends/REFPROP/REFPROPMixtureBackend.h, src/CoolProp.cpp
The REFPROP backend did not override the virtual function ``calc_phase()`` as the other backends do, leaving it undefined per Abstract State.  Change involves:
- At the end of ``REFPROPMixtureBackend::update()``, set value for _Q returned by REFPROP
- At the end of ``REFPROPMixtureBackend::update()``, use _Q to determine the phases value for _phase  
- Return the _phase value in ``REFPROPMIxtureBackend::calc_phase()``
- Pure fluids only; for REFPROP mixtures, a not implemented error is thrown.
- Allows a "Phase" value to be returned from ``PropsSI()`` when using REFPROP backend.
- Allows PhaseSI() to return a "pretty printing" phase string for REFPROP fluids.
If REFPROP changes it's convention for phase values of q, this phase determination logic may need to be updated.
Might need to …
=> Set _phase in REFPROP backend and return it in calc_phase()

include/crossplatform_shared_ptr.h
Fix compilation with VS2017, where std::tr1 is no longer enabled by default
Compilation with VS2017 works flawlessly. `std::shared_ptr` should be used if available.
Not known.
Compilation works.
Somehow related to #1781, but does not check for the presence of a C++11 compiler, but the first VS version (= 2008) supporting `std::shared_ptr`.
=> Use std::shared_ptr if available in VS

src/HumidAirProp.cpp
I introduced checks for the limits mentioned in https://doi.org/10.1080/10789669.2009.10390874 
Use https://github.com/CoolProp/CoolProp/pull/1813/files?w=1 to ignore whitespace changes
Calls that are out of bounds return an error and no longer give nonsense values.
Calls that are just slightly out of bounds will fail, but they might have worked before.
Closes #1811
=> Added limits to the humid air properties, closes #1811

src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
Remove the ambiguity, and this is what REFPROP does.
Correct thermodynamic behavior
A breaking change, might be surprising to users
#1836
=> Never allow two-phase SOS. 

include/Configuration.h, src/Backends/Helmholtz/Fluids/FluidLibrary.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp
important for fluids like 1,1,2-trifluoroethane with commas in them
Allow for the ability to change the delimiter that is used to turn lists of strings into strings.
Allows the base names for fluids to contain a comma, such as many alkane derivatives
None, backwards compatible, changing delimiter between threads might be dangerous
=> Allow list delimiter to be changed

Web/fluid_properties/Mixtures.rst
Document the behaviour that led to #1874 relating to apply_simple_mixing_rule database initialisation behaviour.
Avoid getting caught out by unexpected behaviour.
None?
Documentation change only - looked OK in the GitHub editor preview.
Closes #1874
=> Document apply_simple_mixing_rule initialisation behaviour

Web/coolprop/HighLevelAPI.rst, Web/coolprop/wrappers/Scilab/sample.sce
Fixed a couple of typos that prevent Scilab to run the Coolprop's library under Linux.
=> fixed typo in getos() and else statement

src/Backends/Cubics/CubicsLibrary.cpp
It was annoying specifying all fluid names in caps when adding new fluids to the cubic backend. Simply removing the uppercasing when searching for the fluid in the database is not a good idea cause of the need to specify all possible name spellings in the aliases. Now all fluid names adding to the database uppercased and aliases stay the same.
No need to uppercase fluid names anymore.
I can't come up with any.
I just tried to add new fluid.
```python
import json
import CoolProp.CoolProp as CP
fluid_data = {
'CAS': '79-01-6',
'Tc': 571.0,
'Tc_units': 'K',
'acentric': 0.217,
'aliases': ['tce', "TCE"],
'molemass': 0.131387,
'molemass_units': 'kg/mol',
'name': 'trichloroethylene',
'pc': 4910000.0,
'pc_units': 'Pa'
}
CP.add_fluids_as_JSON("PR", json.dumps([fluid_data]))
T1 = CP.PropsSI("T", …
```
=> Fix uppercase-only fluid naming

Web/coolprop/LowLevelAPI.rst
Order of arguments in the example code using the second_partial_deriv function were not consistent with the source documentation; this is corrected and a second example included to clarify the order of arguments.
```
In [3]: HEOS = CoolProp.AbstractState("HEOS", "Water")                          
In [4]: HEOS.update(CoolProp.PT_INPUTS, 101325, 300)                            
In [5]: HEOS.cpmass()                                                           
Out[5]: 4180.6357765560715
In [6]: HEOS.first_partial_deriv(CoolProp.iHmass, CoolProp.iT, CoolProp.iP)     
Out[6]: 4180.6357765560715
In [7]: HEOS.second_partial_deriv(CoolProp.iSmass, CoolProp.iT, CoolProp.iDmass,
...:  CoolProp.iDmass, CoolProp.iT)                                          
Out[7]: -0.024489736946245212
In [8]: …
```
=> Fix second_partial_deriv example

.gitignore, dev/pcsaft/mixture_binary_pairs_pcsaft.json
Two compounds were misnamed in the file containing PC-SAFT interaction parameters (mixture_binary_pairs_pcsaft.json). "HEPTENE" and "OCTENE" should be "1-HEPTENE" and "1-OCTENE". The .so pattern was also missing from .gitignore.
Now the names here match with those in the json file containing pure compound PC-SAFT parameters.
I guess there's always the chance I accidentally added more typos...
=> fix typos in pcsaft json

src/Backends/Helmholtz/FlashRoutines.cpp, src/Backends/Helmholtz/VLERoutines.cpp
Fixed crash in SaturationSolvers::PTflash_twophase::build_arrays for mixtures with 3 or more components.
changed used index
code crashed hard because of wrong index
Please check, if numerical properties of algorithm are now correct
- *How did you verify that all new functionality works as expected?*
- *How did you verify that all changed functionality works as expected?*
- *How did you verify that the change has not introduced any regressions?*
*Describe the actions you performed (e.g. text you typed, commands you ran, etc.), and describe the results you observed.*  
*Please attach …
=> Fixed crash in PTflash_twophase::build_arrays

wrappers/Python/CoolProp/CoolProp.pyx
Added a reshape operation to the Python wrapper. nD inputs are converted to 1D vectors before PropsSImulti is called and the result is converted back to the original shape.
No more messing with the array shape prior to calling CoolProp.
None
```Python
from CoolProp.CoolProp import PropsSI
import numpy as np
in1 = np.array([280, 290, 300, 280, 290, 300])
in2 = np.array([0, 0.5, 1, 0.0, 0.5, 1])
out1 = PropsSI('P', 'T', in1, 'Q', in2, 'R134a')
out2 = PropsSI('P', 'T', in1.reshape(2, 3), 'Q', in2.reshape(2, 3), 'R134a')
print(np.allclose(out1, np.ravel(out2)))
print(np.allclose(out1.reshape(2, 3), out2))
out1 = PropsSI('P', 'T', in1, 'Q', 0.5, 'R134a')
out2 = PropsSI('P', 'T', in1.reshape(2, 3), 'Q', 0.5, 'R134a')
print(np.allclose(out1, np.ravel(out2)))
print(np.allclose(out1.reshape(2, 3), …
```
=> Allow nD-array input to PropsSI

CMakeLists.txt, wrappers/LibreOffice/Readme.rst, wrappers/LibreOffice/src/scripts/scripts.py.in
Updated the installation routine for the CoolProp python package in the LibreOffice wrapper to use pip. Bundled Python interpreters in LibreOffice doesn't include pip. But as pip itself is platform independent and runs on py2/py3, it will be bundled inside the LibreOffice extension at build time.
This simplifies the installation script inside the LibreOffice wrapper, as the download links for different platforms and ABI versions will be handled by pip. This would also easily allow to install it on arm platforms, if appropriate Python packages would be available.
The updated CoolProp.oxt LibreOffice extension was tested with LibreOffice 7.0.4 on Linux, Windows on macOS.
Extension built for CoolProp-6.4.1 (please rename the file to CoolProp.oxt): …
=> LibreOffice: Use pip for installing CoolProp python package

CMakeLists.txt
A minor correction of CMakeList.txt is done to suppress the configuration error in case of COOLPROP_OBJECT_LIBRARY=ON, which is a switch to build the objects, usually, required to build the ExternalMedia library in OpenModelica; what is done is just skipping the trouble spot of target_link_libraries for dl library in such a case.
Solving the configuration error during the build-process of libExternalMedia.a for the ExternalMedia package.
N/A
All the options of COOLPROP_OBJECT_LIBRARY, COOLPROP_SHARED_LIBRARY, and COOLPROP_STATIC_LIBRARY are checked in independent manner. After then, the make-process of the ExternalMedia library is also tested chaining the cmake project with COOLPROP_OBJECT_LIBRARY=ON.
Closes #2010 if this PR closes an open issue.
=> A minor correction in case of COOLPROP_OBJECT_LIBRARY=ON

src/DataStructures.cpp
The description of Q in the http://www.coolprop.org/coolprop/HighLevelAPI.html#high-level-api is misleading, where it should be "Molar vapor quality" instead of "Mass vapor quality" given the unit description there and the source code implementation.  This commit is intended to fix that documentation by fixing the description implemented in the source code.
No more confusion when using this property.
Null
Null. One word fix so not tested.
NA.
=> Fix typo in iQ description

src/Backends/Cubics/CubicBackend.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.h
Rcomponent in HelmholtzEOSMixtureBackend::calc_alpha0_deriv_nocache is now set using get_fluid_constant(i, igas_constant). For HEOS mixture backend get_fluid_constant() returns fld.EOS().R_u, for cubic backends the ideal gas constant from the configuration variables is used.
Ideal gas part contribution to cubic mixtures was not calculated correctly, as components[i].EOS().R_u was used to receive Rcomponent. This however is never set for the components of cubic mixtures, leading to faulty alpha0 derivatives. This change should fix that.
--
Example calculations were made. After the change resulting thermodynamic properties were mor realistic and close to HEOS mixture values.
```python
import CoolProp
import CoolProp.CoolProp as CP
ch4co2PR = CP.AbstractState("PR","CH4&CO2") …
```
=> Fix Rcomponent in calc_alpha0_deriv_nocache

.github/workflows/cppcheck.yml, .gitignore, dev/ci/colorize_cppcheck_results.py
Note: this builds upon https://github.com/CoolProp/CoolProp/pull/2103
The clang-format will run only on PRs, and only on files touched by this PR (to avoid false positives).
It adds a cppcheck one, with a custom formatter I built.
The cppcheck one is (logically) failing. Errors should be fixed one by one as possible, the rest should be suppressed (either for entire files or inline), until everything passes. Then you can start enforcing. (This is the same as the Catch2 tests, 100% should be passing if you want them to be useful, so you have a Yes or No answer right away)
https://github.com/jmarrec/CoolProp/runs/5724426268?check_suite_focus=true
=> Cppcheck workflow

.github/workflows/BuildSharedLibrary.yml, .github/workflows/coolprop_tests.yml, .github/workflows/documentation.yml, .github/workflows/windows_installer.yml, CMakeLists.txt, dev/extract_version.py
Reacting to a comment on https://github.com/CoolProp/CoolProp/pull/2097#issuecomment-1067484987
@ibell  I honestly don't know if that's what you had in mind or not, and I definitely don't understand what the "Installer package" is supposed to be, is that the `COOLPROP_WINDOWS_PACKAGE` ?
Anyways, this will build the shared lib, and package it up nicely in a version-named tar.gz, uploaded as an artifact.
If you trigger a release (via github, but that effectively creates a tag which is the actual trigger), it will also upload them to the release page.
The HTML version of the documentation is also packaged in a tar.gz and has the same upload treatment. Not sure if that's what you needed either.
---
**Edit**:
- Windows isntaller package, checkout this run: …
=> Github Actions: add shared library and doxygen workflows.

.github/workflows/coolprop_tests.yml, .gitmodules, CMakeLists.txt, dev/generate_headers.py, src/AbstractState.cpp, src/Backends/Cubics/UNIFACLibrary.cpp, src/Backends/Cubics/VTPRBackend.cpp, src/Backends/Helmholtz/FlashRoutines.cpp, src/Backends/Helmholtz/Fluids/Ancillaries.cpp, src/Backends/Helmholtz/MixtureDerivatives.cpp, src/Backends/Helmholtz/VLERoutines.cpp, src/Backends/Incompressible/IncompressibleBackend.cpp, src/Backends/Incompressible/IncompressibleFluid.cpp, src/Backends/REFPROP/REFPROPMixtureBackend.cpp, src/Backends/Tabular/TabularBackends.cpp, src/Backends/Tabular/TabularBackends.h, src/CPstrings.cpp, src/CoolProp.cpp, src/DataStructures.cpp, src/Helmholtz.cpp, src/HumidAirProp.cpp, src/MatrixMath.cpp, src/ODEIntegrators.cpp, src/PolyMath.cpp, src/Tests/CoolProp-Tests.cpp, src/Tests/Tests.cpp, src/Tests/catch_always_return_success.cxx, src/Tests/test_main.cxx
Bump Catch to Catch 2.x
register catch2 tests as `ctest`
Note: this build upon the `cpp_review` branch, so review https://github.com/CoolProp/CoolProp/pull/2104 or look at https://github.com/jmarrec/CoolProp/compare/cpp_review...catch2 for a clean diff
More modernizing
none.
Ran the Catch2 tests
=> Bump Catch  1 to Catch v3.0.0-preview4

dev/extract_version.py
I think I know why mac is failing, it's because of the newline char... testing it out. Worse case scenario, I'll make the replacement in python instead of using sed in bash
example failed run: https://github.com/CoolProp/CoolProp/runs/5784053724?check_suite_focus=true
=> Fix mac cibuildwheel

src/Backends/Cubics/CubicBackend.cpp, src/Backends/Cubics/VTPRBackend.cpp, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, src/Backends/Helmholtz/ReducingFunctions.h, src/Backends/REFPROP/REFPROPMixtureBackend.cpp
Bound-checks were added to setter and getter functions:
- set_binary_interaction_double(const std::size_t i, const std::size_t j, const std::string &parameter, const double value)
-  set_binary_interaction_string(const std::size_t i, const std::size_t j, const std::string &parameter, const std::string &value)
-   get_binary_interaction_double(const std::size_t i, const std::size_t j, const std::string &parameter)
-    apply_simple_mixing_rule(std::size_t i, std::size_t j, const std::string &model)
-  set_cubic_alpha_C(const size_t i, const std::string &parameter, const double c1, const double c2, const double c3)
-   set_fluid_parameter_double(const size_t i, const std::string &parameter, const double value)
-    get_fluid_parameter_double(const size_t i, const std::string &parameter) …
=> Add bound-check to setter and getter functions

.github/workflows/python_cibuildwheel.yml
Add a py37 build for Windows x64
@ibell
=> Missing a py37 build for Windows x64 + fix py38 win32 and py39 win32

.github/workflows/python_cibuildwheel.yml
I'm opening this because I've done the legwork and we discussed it on a couple of occasions already.
Pros:
* It's less verbose and therefore perhaps simpler to read.
Cons:
* It's slower (about 16minutes versus 8minutes in the current setup)
* Primarily because one runner will build both x86_64 and win32 for eg
* because it doesn't use the COOLPROP_CMAKE (which will build the shared library bit in parallel with `-j $(nproc)`)
* I'm pretty sure there is something quite wrong with the linux configs... the whl ends up being 43 MB versus 6MB in the current cibuildwheel setup (and 2MB on mac, 1.7 on windows...), I don't know why. (nor am I interested in figuring it out)
* **edit**: fixed by putting back COOLPROP_CMAKE for linux
I'm not really in favor of making this "simplification" (edit: now …
=> Simplify CoolProp python bindings cibuildwheel

include/CoolProp.h, include/CoolPropLib.h, src/CoolProp.cpp, src/CoolPropLib.cpp
Props1SImulti new function in CoolProp and Props1SImulti and PropsSImulti to CoolPropLib
Function Props1SImulti was added to CoolProp. It is the Props1SI function but with multiple outputs possible, comparable to PropsSImulti.
Props1SImulti and PropsSImulti were added to CoolPropLib
Enables the user to acces multiple non-thermodynamic-state-dependend fluid properties at once.
None
Functions were tested using the Mathematica wrapper, see PR #2085
=> New functions for CoolPropLib

include/CoolPropLib.h, src/CoolPropLib.cpp
AbstractState_get_mole_fractions_satState returns mole fractions for saturated "liquid" or "gas" phases
AbstractState_keyed_output_satState returns keyed output for saturated "liquid" or "gas" phases
AbstractState_backend_name returns the backend name for an AbstractState
add_fluids_as_JSON can be called from the High-Level.
Changes to AbstractState_get_phase_envelope_data
Adds functionality to the High-Level-Interface.
AbstractState_get_phase_envelope_data returns the actual length of the array and throws an error should there not be enough memory allocated.
Changes to AbstractState_get_phase_envelope_data might imply refactoring of wrappers (could only find it in Julia wrapper)
Functions were tested using the Mathematica wrapper, see PR #2085
Based on PR #2133 and #2134
=> AbstractState functions for CoolPropLib

src/Ice.cpp
Email reply from Dr Bell.
"""
Yes, I think you are right. From the IAPWS release:
I think I overlooked the p subscript when I was implementing that, now more than a decade ago! Can you please file a pull request fixing it?  I wonder how nobody noticed before.
================================================================================
Dear Dr Bell,
I came across the density of ice function in CoolProp as follows. (https://coolprop.dreamhosters.com/binaries/sphinx/_static/doxygen/html/_ice_8cpp_source.html)
double rho_Ice(double T, double p)
{
#ifndef __powerpc__
// Returned value is in units of kg/m3
return 1/g_Ice(T,p);
#else
return 1e99;
#endif
}
Shouldn’t it be dg_dp_Ice instead of g_ice?
I confirmed with vmolar and get the same value as rho_ice using dg_dp_ice.
Thanks. 
"""
Used …
=> Corrected rho_ice route by replacing g_ice with dg_dp_Ice in Ice.cpp

dev/pcsaft/all_pcsaft_fluids.json, dev/pcsaft/pcsaft_fluids_schema.json, include/DataStructures.h, include/PCSAFTFluid.h, src/Backends/PCSAFT/PCSAFTBackend.cpp, src/Backends/PCSAFT/PCSAFTBackend.h, src/Backends/PCSAFT/PCSAFTFluid.cpp, src/DataStructures.cpp, src/Tests/CoolProp-Tests.cpp
The flash algorithm for the PC-SAFT backend was updated to improve its performance. Additionally, the association term for the PC-SAFT EOS was expanded to also support other association schemes, in addition to the default 2B scheme used in the earlier code.
The flash algorithm is, generally, faster and more reliable, although it could still be improved. Also, a wider range of association schemes can be used.
New bugs might have been introduced.
I ran the Catch tests in CoolProp-Tests.cpp. All the PC-SAFT tests passed. Of all the tests only 285/51440 assertions failed, and it appeared that many of these were because I didn't have Refprop installed. For comparison, when I run the tests on the current master branch 306/51436 fail, and some of those that fail are for PC-SAFT tests. So, this …
=> improve PC-SAFT flash

src/Backends/Cubics/CubicBackend.cpp, src/Backends/Cubics/CubicBackend.h, src/Backends/Cubics/CubicsLibrary.cpp, src/Backends/Cubics/CubicsLibrary.h
fluid_param_string and get_JSONstring were added to the cubic backend. Implementation is comparable to HelmholtzEOSMixturebackend See PR #1371.
Minor changes to CubicBackend.cpp were made:
- If phase is imposed, it is returned instead of always returning gas phase for mixtures
- TODO to return the correct phase is not properly fixed though
Enables the user to get the JSON for a cubic fluid during runtime
None
Functions were tested using the Mathematica wrapper, see PR #2085
based on PR #2133
=> Add fluid_param_string and get_JSONstring to cubic backend

CoolPropBibTeXLibrary.bib, Web/coolprop/PCSAFT.rst, Web/coolprop/index.rst, Web/index.rst, dev/pcsaft/all_pcsaft_fluids.json, dev/pcsaft/mixture_binary_pairs_pcsaft.json
I added a page in the docs for the PC-SAFT equation of state. I also added the references for the PC-SAFT fluid parameters to the BibTeX file.
=> add PCSAFT page in docs

include/Solvers.h, src/Backends/Helmholtz/FlashRoutines.cpp, src/Backends/Helmholtz/Fluids/Ancillaries.cpp, src/Backends/Helmholtz/VLERoutines.cpp, src/Backends/Helmholtz/VLERoutines.h, src/Solvers.cpp
When updating an HEOS abstract state from density and energy, crashes (`ValueError` thrown) can occur when the density is very near the critical density. This PR fixes this behavior and prevents the exception.
`HSU_D_flash` is called when updating with D and U (as well as other combinations). As one of the first steps in the flash routine, the saturation points are determined at the given density (`saturation_D_pure`). However, when near the critical density, instabilities in the solver routines cause an exception. This PR utilizes a few strategies to prevent this:
- When inverting the ancillary curve, if the density is outside of the ancillary curve's domain, extrapolate in the secant solver. 
- When using the 2D Newton solver within `saturation_D_pure`, prevent the calculation of a …
=> Prevent crashes near critical density due to saturation calc

src/Backends/Helmholtz/FlashRoutines.cpp
DQ is poorly defined (not unique) for densities above critical density. Provide the user better feedback when they try to do this, but do not give them a non-unique answer that might give them trouble later. This PR provides the user more direct feedback warning them about this, but does not try to guess at one of the non unique solutions.
The HEOS defines properties in terms of density (D) and temperature (T). If we provide a DQ input pair, the first thing that the solver attempts to do is to find the associated temperature. However, above the critical density, temperature is not a function of density and therefore no unique state exists. 
For all (most?) fluids, DQ inputs are not unique for densities above the critical density. Take for example the following plots of R134a, water, …
=> Provide better feedback for bad DQ inputs

Readme.rst, Web/index.rst
As discussed here:
https://groups.google.com/g/coolprop-users/c/l_aY4vTT58Q
Change links in readme and docs to point to github discussions.
I think the github discussions has a better format to discuss programming questions, it is easier to read, and we have options such as choosing the right answer, upvote etc. which are similar to stackoverflow.
Additionally, we would have all content (issues + discussions) in only one place, making it easier to search things.
It would also make it easier to reference things, for example, issues that could be open based on discussions.
=> Change links from Google group to GitHub discussions

dev/fluids/R1233zd(E).json, src/Backends/Helmholtz/FlashRoutines.cpp
Correct issues that lead to poor performance of R1233zd(E) near the saturation line. This closes issue #2142. The steps taken to do so are:
1) Remove the poorly performing hL ancillary.
2) Add a 0.01K cushion to the `T_max` that is acquired from an ancillary. 
3) Reverse the 0.01K cushion on `T_min` the is produced by an ancillary.
While item 3 was not part of the original investigation, it might prevent future issues. 
R1233zd(E) now performs as expected near the saturation curve. The adjustments to `T_max` and `T_min` may also assist other fluids near the saturation curve under HSU_P inputs. 
The lack of an ancillary may slow calculations with R1233zd(E). Furthermore, no robust investigation into the other ancillary functions has been carried out. Future work should attempt to refit the …
=> Topic 2142

include/CPstrings.h, include/CoolPropFluid.h, include/DataStructures.h, include/IncompressibleFluid.h, src/Backends/Helmholtz/VLERoutines.h, src/HumidAirProp.cpp
With the recent breaking changes made with fmt, it is no longer possible to build CoolProp using the latest release of fmt (10.0.0).
The main issue is that enums no longer get automatically converted to int, even when using `sprintf` and the `%d` specifier explicitly.
To resolve this issue, every enum that is used in a format call needs to have a `format_as` overload **in the same namespace**. This feature is only available since fmt 9.0.0, hence the `FMT_VERSION >= 90000` guard.
As suggested, the module was also updated to the latest version.
Support newer versions of fmt, without …
=> Update fmt submodule to 10.0.0

.github/workflows/python_cibuildwheel.yml
This may fix the failing python_cibuildwheel workflows.
Changed to older Cython version to fix `cpdef` deprication.
=> Fix failing python_cibuildwheel workflows

CoolPropBibTeXLibrary.bib, dev/fluids/CarbonDioxide.json, include/CoolPropFluid.h, src/Backends/Helmholtz/Fluids/FluidLibrary.h, src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp, src/Backends/Helmholtz/TransportRoutines.cpp, src/Backends/Helmholtz/TransportRoutines.h
Implements the newer viscosity model for CO2 from Laesecke, JPCRD, 2017.
- More accurate viscosity estimation.
- Increased accuracy in conductivity estimation due to dependence on the viscosity model.
Not known.
Verification has been done for all the values given in Table. 6 and Table. 8 of Laesecke and Muzny, JPCRD 2018.
Note: P=0MPa corresponds to `inf` due to exception in solution of EOS.
=> implemented VISC LAESECKE-JPCRD-2017-CO2

include/CoolPropLib.h, src/CoolPropLib.cpp, src/CoolPropLib.def
Fugacity lookups `get_fugacity`, `get_fugacity_coefficient`, and `get_fugacity_coefficients` cannot be wrapped with Julia functions as they currently are in this repo. This is in effort to enable using `CoolProp.jl` to return fugacity which is currently  a missing feature (an issue was created [here](https://github.com/CoolProp/CoolProp.jl/issues/31) in `CoolProp.jl`). 
Allows fugacity calls to be wrapped with Julia code directly in `CoolProp.jl`. We have found that using low-level Julia-wrapper commands is approximately 10x faster than using `Pycall` within Julia to call CoolProp low-level commands. This is a surmountable benefit when incorporating CoolProp calls with iterative numerical models of fluid systems within the Julia language that require fugacity lookups.
Unsure of any …
=> Add fugacity functions needed for compatability with `CoolProp.jl` pkg

include/CoolPropLib.h, src/CoolPropLib.cpp, src/CoolPropLib.def
Files Modified: CoolPropLib.cpp, CoolPropLib.h,  CoolPropLib.def
Changes:
* Added AbstratState_second_partial_deriv Function:
Location: Added in CoolPropLib.cpp
Description: The AbstratState_second_partial_deriv function calculates the second partial derivative and is already implemented in AbstractState.cpp so I only had to implement it to the CoolPropLib.
* Added AbstractState_first_two_phase_deriv Function:
Location: Added in CoolPropLib.cpp
Description: The first_two_phase_deriv function calculates the first derivative in a two-phase region of a thermodynamic and is already implemented in AbstractState.cpp so I only had to implement it to the CoolPropLib.
* Header File Updates:
File: CoolPropLib.h
Changes: Added functions and docstrings for second_partial_deriv and …
=> Added second_partial_deriv and  first_two_phase_deriv

Web/index.rst
We have changed the name of the app
CuadernoDeProblemas -> pSolver.
pSolver can be used on English and Spanish
Updating the reference to the app
Update the links
None
New links verified
=> App name change: CuadernoDeProblemas -> pSolver, Update index.rst

CoolPropBibTeXLibrary.bib, dev/fluids/R1336mzz(E).json
As requested in Issues #2127 and #2307, this pull request aims to add R1336mzz(E) to the list of fluids of CoolProp.
I added the JSON file of the supplementary information zip-file from Akasaka-IJT-2023 (https://doi.org/10.1007/s10765-022-03143-5) in the fluids directory. Then i created the corresponding BibTeX entry and referenced it in the JSON file at parameter "BibTeX_EOS".
Please let me know, if there is anything else to do in order to complete the addition of R1336mzz(E).
=> Addition of EoS JSON of R1336mzz(E) from Akasaka-IJT-2023

include/CoolPropLib.h, src/CoolPropLib.cpp
A few new C interface functions have been added. They enable accessing some information which is currently not available in the C interface. I guess they were just missing.
I did not yet add docstrings to the headers. I didn't know where to copy the descriptions from (as it surely exists somewhere in the library).
A more complete C interface?
Future maintenance?
We already use this interface in the TILMedia library. So, the interface is ready to use. However, not all failure cases (try/catch) are tested. The interface functions have been duplicated and modified from existing functions in the same file, to meet the same requirements.
=> New C Interface Functions

dev/Tickets/2295.py, src/Backends/Incompressible/IncompressibleFluid.cpp, src/PolyMath.cpp
The base input values of incompressible fluids can cause a division by zero when calculating properties at this particular temperature or composition.
No more exceptions when calculating at base temperature or composition.
Have a look at `dev\Tickets\2295.py`: 
```shell
python .\dev\Tickets\2295.py
Exactly the middle between maximum and minimum temperature does not work for PHE.
..\..\src\PolyMath.cpp (511): A fraction cannot be evaluated with zero as denominator, x_in-x_base=0.000000
Exactly the middle between maximum and minimum temperature does not work for Water.
..\..\src\PolyMath.cpp (511): A fraction cannot be evaluated with zero as denominator, x_in-x_base=0.000000
Exactly the middle between maximum and minimum temperature does not work for TVP1.
..\..\src\PolyMath.cpp (511): A …
```
=> Fix base temperature and composition problems for incompressible fluids

include/CoolPropLib.h
Conditionally include `stdbool.h` when including `CoolPropLib.h` from C. 
`stdbool.h` will not need to be included before `CoolPropLib.h` in C programs. This conforms to the [include what you use](https://google.github.io/styleguide/cppguide.html#Include_What_You_Use) rule from the style guide.
None I can think of.
- Compiled a C99 program including `CoolPropLib.h` without including `stdbool.h` beforehand.
- Still compiles with C89 when using typedef for bool
=> Include stdbool for C interface

src/CoolPropLib.cpp
Attempt to make calls to `AbstractStateLibrary` class thread-safe. Not so familiar with multi-threading so, there might be a better solution. No changes have been made to `AbstractState` class and if I understand correctly, methods like `AbstractState::update()` are prone to data races.
Handles to `AbstractState` objects can be obtained within parallel loops using `Threads.@threads` macro when working with Julia wrapper.
None known so far
**Test file** : Julia source `test-CP.jl`
```julia
pathCoolProp = "CoolProp"
(pathCoolProp in Base.DL_LOAD_PATH) || push!(Base.DL_LOAD_PATH, pathCoolProp)
(pathCoolProp in LOAD_PATH) || push!(LOAD_PATH, pathCoolProp)
import CoolProp as CP
function geteos(name::AbstractString, backend::AbstractString="HEOS")
handle = CP.AbstractState_factory(backend, …
```
=> Make AbstractStateLibrary class thread-safe

wrappers/MATLAB/README.rst
This commit adds a link to the MATLAB wrapper `README.md` a repo that contains information and code to facilitate calling `CoolProp` through MATLAB's C interface with the `CoolProp` shared library as discussed in [Discussion 2368](https://github.com/CoolProp/CoolProp/discussions/2368)
Some explanatory text about MATLAB's C interface and a link to the `coolprop-mat` repo which contains MATLAB source code to facilitate calling the `CoolProp` shared library to the `README.rst` of the MATLAB wrapper.
Makes potential MATLAB users aware of an additional avenue to call `CoolProp`.
Checked …
=> Add link to `coolprop-mat` repo

.github/workflows/mathcad_builder.yml
Mathcad builder is failing due to permissions issues on accessing repository secrets to get required build libraries from PTC.
The only reason the Mathcad builder exists is to provide a binary on the scheduled nightly builds.  It is not necessary to check the Mathcad wrapper every time a change is made to CoolProp.  So, the following line in the build job skips the build if this is a push (direct commit) or a Pull Request to the repository.
```
if: github.event_name != 'push' && github.event_name != 'pull_request'
```
I believe this will allow the script to run when called directly (a 'workflow_call' event) from the nightly build script and the nightly binary file will still be built.
Removes Mathcad Build failures from standard pushes and PRs
The only drawback would be if a change is …
=> Bypass Mathcad builder on pushes and PRs

.github/workflows/release_all_files.yml, .github/workflows/release_get_artifact.yml
Simple updates to workflows:
- release_all_files.yaml
- release_get_artifacts.yaml  
to create uniquely named artifacts from sub-workflows and then merge them on download for deployment.
Should fix the nightly builds, which are currently failing after updating to upload/download-artifact@v4.  This version requires artifacts from each workflow to be uniquely named.  This patch implements that change with a workflow suffix on each artifact and then downloads them all according to pattern "binaries-*" and merges them into the same directory for deployment.
NOTE: It is not necessary to upload a new, single artifact with the merged files.
None.  No impact on the code; only the nightly builds (which are currently failing).  Skipping CI workflows as this change does not impact them, only the …
=> Update the Release Workflow for upload/downlaod-artifact@v4 [skip ci]

.github/workflows/libreoffice_builder.yml
Fix build action for LibreOffice extension.
- Run apt-get update to sync package index files before installing libreoffice as a build dependency. This fixes failing builds due to download errors of outdated packages.
- Update to actions/checkout@v4 as v3 uses deprecated Node.js version.
Build action will run again.
None
Tested the updated build workflow on GitHub. It works fine without any errors or warnings.
Fixes the issue seen by @henningjp at https://github.com/CoolProp/CoolProp/commit/214a6147dfbd57600fdc728b0bfd1a291fb11db9#comments
=> Fix libreoffice_builder

src/Backends/PCSAFT/PCSAFTBackend.cpp, src/Tests/CoolProp-Tests.cpp
The ion term in the PC-SAFT code was updated to use the temperature dependent hard sphere diameter (d) instead of sigma. This is a fix for issue [2338](https://github.com/CoolProp/CoolProp/issues/2338).
Fixes the ePC-SAFT model so it give correct results.
There's always the chance a mistake was introduced.
I ran the Catch tests before and after making changes. The test results were exactly the same and all PC-SAFT tests passed.
``Closes #2338``
=> Use temperature dependent hard sphere diameter for ion term in ePC-SAFT

.github/workflows/python_buildwheels.yml, .github/workflows/python_cibuildwheel.yml, .github/workflows/release_all_files.yml, wrappers/Python/setup.py
Updated setup.py, python_cibuildwheel.yml, and python_buildwheels.yml
setup.py
- Replaced distutils as per PEP 632 with setuptools and packaging
python_cibuildwheel.yml
- Added the module packaging to the dependencies
- Added 313 to the list of python versions
- Replaced python-version: 3.12.x with python-version: 3.13.x
- Removed some redundant lines of codes related to version specifically excluded architecture (for example ARM64 windows python 36) since these architectures are generically already excluded and/or the python version is no longer supported.
python_buildwheels.yml
- Replaced pypa/cibuildwheel@v2.17.0 with pypa/cibuildwheel@v2.21.3
- Replaced python-version: 3.12.x with python-version: 3.13.x
Python 3.13 should now be supported
There is still an error left-over related to …
=> Python 3.13 and replace distutils with setuptools PEP 632 – Deprecate distutils

wrappers/Python/CoolProp/Plots/Common.py
Correct `np.NaN` to `np.nan` in `wrappers/Python/CoolProp/Plots/Common.py` (see also: https://github.com/CoolProp/CoolProp/issues/2437#issue-2649098703)
No error if using numpy >= 2 (https://numpy.org/doc/stable/release/2.0.0-notes.html)
unknown
Only tested in own project
=> Fix np.NaN for numpy >=2

wrappers/Python/CoolProp/Plots/Common.py
When i tried to plot log(p)-h-diagrams there always had been an issue in the `common.py` file in line 481. By deleting the `Isoline, self` expression between the clips of super in this line, i could fix this and the plots were generated. So i made this pull request and hope you will fix the master that every coolprop user can make plots again.
=> Fix Plots of log-p-h diagrams

include/CoolPropPlot.h, src/CoolPropPlot.cpp
This pull request contains a relatively crude rewrite of Python's plotting into C++. The code only takes care of the calculations of the limits and isolines in SI units for different plot types (ph and Ts diagrams are extensively checked but others that are supported in Python have also been tried and seem to work). How the actual drawing is done is left to the end-user.
Usage example can be found in the unit tests at the bottom of `CoolPropPlot.cpp`.
Thank you for creating this really cool library. The code here is a cleaned-up version of what we are using in our fork at Dewesoft for our new Thermodynamics module, and it makes sense to open-source our modifications back into CoolProp as we think they might be generally useful.
It seems like at the moment the only way to really plot with …
=> Support plotting in C++

CMakeLists.txt, wrappers/Python/setup.py
Required addition of unicode support
Squashes copious warnings in MSVC
=> Bump fmtlib to 11.1.3

src/Backends/REFPROP/REFPROPMixtureBackend.cpp
There were a number of problems with D,U inputs in the REFPROP backend.
1. The output for enthalpy was accidentally that of entropy
2. The saturated liquid density was for some reason not being set at all (must have been leftover debugging or something)
=> Fix a bunch of bugs with D,U inputs in REFPROP backend

wrappers/Python/setup.py
Test whether renaming the project in setup.py is enough
Based on this PEP: https://peps.python.org/pep-0503/
=> Project names are required to be all lowercase

.gitmodules, CMakeLists.txt, include/Helmholtz.h, src/Helmholtz.cpp
Found some issues in log function of mcx. Should update the tests to use autodiff probably
See #2484; this closes one set of the failures, in a more robust way. Might revisit this approach with autodiff instead because of the issues with the log function
=> Switch EOS tests to multicomplex

wrappers/Python/CoolProp/AbstractState.pxd, wrappers/Python/CoolProp/AbstractState.pyx, wrappers/Python/CoolProp/cAbstractState.pxd
The C++-function set_cubic_alpha_C seems to be missing from the python wrapper, so I added it.
The function set_cubic_alpha_C will be available in python, allowing the user to change the alpha function of cubic equations of state to Twu or MC and set the fluid specific parameters c1, c2 and c3.
None.
I compared the density calculation of PR with and without the Twu alpha function for a mixture of methane and ethane. The calculated densities differ, as expected, and match those that I get when using CoolProp with the Mathematica wrapper where the set_cubic_alpha_C function is already implemented.
I can do a more "formal" test and post the code if you wish, but since I only added an existing C++ function to the python wrapper I feel like this should be enough.
No open issue that I am aware …
=> Add set_cubic_alpha_C function to python wrapper

src/Backends/REFPROP/REFPROPMixtureBackend.cpp
The ``COOLPROP_REFPROP_ROOT`` environment variable can now be set in the operating system which is used when CoolProp needs to load REFPROP. If it is not used, the normal, but not recommended approach can still be used, as this environment variable "wins".  After the shared library of REFPORP gets loaded, the SETPATHdll function is used, so absolute paths should no longer be used with the REFPROP backend.
To support custom REFPROP use, it is recommended to copy REFPROP folders to local location and 
Much better integration with REFPROP
Closes #2501
=> Enable COOLPROP_REFPROP_PATH environment variable

Web/coolprop/Configuration.rst, include/Configuration.h
Allow the user to overwrite configuration variables at program load by setting environment variables (prefixed with ``COOLPROP_``) in the operating system to overwrite the values of the configuration variables
Gives greater flexibility. In some environments like Excel, it is difficult or impossible to change configuration variables by other means.
None - fully backwards compatible. Negligible overhead to read the environment variables.
Closes #2519
=> Overwrite config with env

.github/workflows/docs_docker-run.yml, wrappers/Python/CoolProp/Plots/ConsistencyPlots.py
Bug in GH with #2616 this is a duplicate that seems to be correct 
Consistency plots were not including failures at all, this fixes this, and allows the calls to happen in parallel with a process_map
=> Fix consistency plots

Web/fluid_properties/Mixtures.rst, include/DataStructures.h, src/Backends/Helmholtz/MixtureParameters.cpp
This PR makes two changes to improve mixture pair management:
* `apply_simple_mixing_rule` and `set_interaction_parameters` were exposed in the CoolProp Python library but not its C++ library.
* Previously, calling `apply_simple_mixing_rule` could break the default mixing rules, if the mixing rules hadn't already been initialized. This has caused confusion and bugs in the past; see #1874 and https://github.com/CoolProp/CoolProp/issues/2082#issuecomment-1024954744.
I also removed the unused `mixturebinarypairlibrary_default` static variable.
More complete and consistent interfaces across CoolProp's supported language bindings, and less error-prone usage of mixture pair support.
Minimal increase in API surface and an extra runtime check
We've been running this in an internal fork of …
=> Improvements to mixture pair management

.github/workflows/windows_installer.yml
Dropped in Windows server 2025 image; see https://github.com/actions/runner-images/issues/12464
=> CI add InnoSetup

wrappers/Fluent/Example_windows_UDF.cpp, wrappers/Fluent/README.rst
I added how to use the wrapper for Windows through the shared library. There might be a better way using the static library, but I believe this method works for 99% of use cases.
There was no guide for how to use CoolProp with Fluent in Windows anywhere
Worked with both Fluent internal compiler and VS compiler
=> Add Windows Instructions and example for Fluent Wrapper
